cubes:
  - name: products
    sql_table: public.products
    data_source: default

    joins:
      - name: product_categories
        sql: "{CUBE}.product_category_id = {product_categories}.id"
        relationship: many_to_one

    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true

      - name: name
        sql: name
        type: string

      - name: description
        sql: description
        type: string

      - name: created_at
        sql: created_at
        type: time

    measures:
      - name: count
        type: count

    pre_aggregations:
      # Pre-aggregation definitions go here.
      # Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started

